// Mocks generated by Mockito 5.4.4 from annotations
// in nana/test/src/features/home/domain/products_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nana/core/util/resources/common_dependencies.dart' as _i5;
import 'package:nana/features/home/data/models/product_model.dart' as _i6;
import 'package:nana/features/home/domain/repository/home_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppExceptions, List<_i6.ProductModel>>> products(
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #products,
          [
            limit,
            offset,
          ],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.AppExceptions, List<_i6.ProductModel>>>.value(
            _FakeEither_0<_i5.AppExceptions, List<_i6.ProductModel>>(
          this,
          Invocation.method(
            #products,
            [
              limit,
              offset,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppExceptions, List<_i6.ProductModel>>>);
}
